spring:
  datasource:
    username: root
    password: 123123
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull




#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.github.flj.guavatest.entity

# 通用mapper 配置 自动生成dao层代码
mapper:
  plugin: tk.mybatis.mapper.generator.MapperPlugin
  Mapper: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL